[package]
name = "wasm"
version = "0.1.0"
authors = ["luppy@appkaki.com"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
# crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
app          = { path = "../app" }    # Import path `../app` as Watch Face
lvgl         = { path = "../lvgl" }   # Import path `../lvgl` as LVGL library

[dependencies.web-sys]
version = "0.3.4"
features = [
  'ImageData',
  'CanvasRenderingContext2d',
]
