[package]
name = "wasm"
version = "0.1.0"
authors = ["luppy@appkaki.com"]
edition = "2018"

[lib]
crate-type = ["staticlib"]
# crate-type = ["cdylib"]

[dependencies]
pinetime-macros     = "1.0.1"  # Safe Wrapper Macros for Mynewt on PineTime Smart Watch: https://crates.io/crates/pinetime-macros
pinetime-mynewt     = "1.0.1"  # Mynewt Bindings for PineTime Smart Watch: https://crates.io/crates/pinetime-mynewt
pinetime-lvgl       = "1.0.1"  # LVGL Bindings for Mynewt on PineTime Smart Watch: https://crates.io/crates/pinetime-lvgl
pinetime-watchface  = "1.0.1"  # Watch Face Framework for Rust + Mynewt on PineTime Smart Watch: https://crates.io/crates/pinetime-watchface
barebones-watchface = "1.0.1"  # Barebones Watch Face for Rust + Mynewt on PineTime Smart Watch: https://crates.io/crates/barebones-watchface
