name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch cache for Rust Toolchain
      id:   cache-rust
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    #- name: Install wasm-pack
    #  if:   steps.cache-rust.outputs.cache-hit != 'true'  # Install wasm-pack if not found in cache
    #  run:  cargo install wasm-pack

    - name: Check cache for emscripten
      id:   cache-emsdk
      uses: actions/cache@v2
      env:
        cache-name: cache-emsdk
      with:
        path: /tmp/emsdk
        key:  ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Install emscripten
      if:   steps.cache-emsdk.outputs.cache-hit != 'true'  # Install emscripten if not found in cache
      run:  |
        # Based on https://emscripten.org/docs/getting_started/downloads.html
        cd /tmp

        # Get the emsdk repo
        git clone https://github.com/emscripten-core/emsdk.git

        # Enter that directory
        cd emsdk

        # Download and install the latest SDK tools.
        ./emsdk install latest

        # Make the "latest" SDK "active" for the current user. (writes .emscripten file)
        ./emsdk activate latest

        # Activate PATH and other environment variables in the current terminal
        source ./emsdk_env.sh

        # Show version
        emcc --version
        emcc --version        

    - name: Build LVGL
      run:  |
        # Add emscripten to the PATH
        source /tmp/emsdk/emsdk_env.sh

        # Build LVGL app: wasm/lvgl.html, lvgl.js, lvgl.wasm
        wasm/lvgl.sh

    - name: Show files
      run:  set ; pwd ; ls -l

    - name: Upload Outputs
      uses: actions/upload-artifact@v2
      with:
        name: wasm
        path: |
          wasm/*.html
          wasm/*.js
          wasm/*.wasm

    #- name: Run tests
    #  run: cd tests; python ./build.py