name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install emscripten
      run:  |
        # Based on https://emscripten.org/docs/getting_started/downloads.html
        cd /tmp

        # Get the emsdk repo
        git clone https://github.com/emscripten-core/emsdk.git

        # Enter that directory
        cd emsdk

        # Download and install the latest SDK tools.
        ./emsdk install latest

        # Make the "latest" SDK "active" for the current user. (writes .emscripten file)
        ./emsdk activate latest

        # Activate PATH and other environment variables in the current terminal
        source ./emsdk_env.sh

        # Show version
        emcc --version
        emcc --version        

    - name: Build LVGL
      run:  |
        source /tmp/emsdk/emsdk_env.sh
        wasm/lvgl.sh

    - name: Show files
      run:  set ; pwd ; ls -l

    - name: Upload Outputs
      uses: actions/upload-artifact@v2
      with:
        name: wasm
        path: wasm/*

    #- name: Run tests
    #  run: cd tests; python ./build.py
